"""add missing free column to pattern

Revision ID: 0105941c5784
Revises: e8daa0a18d92
Create Date: 2024-05-01 09:54:27.039008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0105941c5784'
down_revision = 'e8daa0a18d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_free', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.drop_column('is_free')

    # ### end Alembic commands ###
