"""category table update

Revision ID: 191f87d0b3dc
Revises: 39815abee173
Create Date: 2024-04-30 18:40:05.492592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191f87d0b3dc'
down_revision = '39815abee173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_categories_parent_id', 'categories', ['parent_id'], ['id'])
        batch_op.drop_column('parent_category')

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_column('stripe_payment_intent_id')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('stripe_payment_intent_id', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_category', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
