"""add stripe columns to purchase table

Revision ID: 1f07bbac2131
Revises: eb17f2dada4b
Create Date: 2024-05-05 15:28:02.326091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f07bbac2131'
down_revision = 'eb17f2dada4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_product_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('stripe_price_id', sa.String(), nullable=True))
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('stripe_price_id')
        batch_op.drop_column('stripe_product_id')

    # ### end Alembic commands ###
