"""pattern table edit

Revision ID: 7598408df1ec
Revises: 191f87d0b3dc
Create Date: 2024-04-30 20:10:48.607867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7598408df1ec'
down_revision = '191f87d0b3dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
