"""columns moved from purchase to pattern

Revision ID: 899414a27c51
Revises: 1f07bbac2131
Create Date: 2024-05-05 17:31:39.624124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899414a27c51'
down_revision = '1f07bbac2131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_product_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('stripe_price_id', sa.String(), nullable=True))

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_column('stripe_price_id')
        batch_op.drop_column('stripe_product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_product_id', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('stripe_price_id', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.drop_column('stripe_price_id')
        batch_op.drop_column('stripe_product_id')

    # ### end Alembic commands ###
