"""name change

Revision ID: e8daa0a18d92
Revises: f4f3bb2046f5
Create Date: 2024-04-30 21:03:38.119665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8daa0a18d92'
down_revision = 'f4f3bb2046f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
